steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=https://vhppjwjojxykbsmutsnr.supabase.co'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocHBqd2pvanh5a2JzbXV0c25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2MDk3MTgsImV4cCI6MjA4MjE4NTcxOH0.9pauPXuLspBWG5eKioiXjnOxGGyYIOr2yqAp7u_uzh0'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/edp-attendance-app:$COMMIT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/edp-attendance-app:$COMMIT_SHA'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'edp-attendance-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/edp-attendance-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--port'
      - '8080'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/edp-attendance-app:$COMMIT_SHA'
